name: generate-docs

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  generate:
    runs-on: windows-2025
    permissions:
      contents: write

    steps:
      - name: Checkout clore
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
          activate-environment: true
          cache: true
          locked: true

      - name: Restore compiler cache
        uses: actions/cache@v5
        with:
          path: .cache/sccache
          key: Windows-sccache-${{ github.sha }}
          restore-keys: |
            Windows-sccache-

      - name: Start sccache
        run: sccache --start-server

      - name: Build
        run: pixi run build

      - name: Generate documentation
        run: |
          ./build/RelWithDebInfo/bin/clore `
            --compile-commands build/RelWithDebInfo/compile_commands.json `
            --source-dir src `
            --output-dir generated `
            --log-level info `
            --dry-run

      - name: Package documentation
        run: Compress-Archive -Path generated/* -DestinationPath clore-docs.zip

      - name: Upload documentation artifact
        uses: actions/upload-artifact@v7
        with:
          name: clore-docs
          path: clore-docs.zip
          retention-days: 30

      - name: Stop sccache
        run: sccache --stop-server
