name: Publish documentation

on:
  push:
    branches: [ "main" ]
    paths:
      - "docs/**"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Publish documentation
        uses: clice-io/docs@main
        with:
          project: clore
          token: ${{ secrets.PUBLISH_DOCS }}
