name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: [ "windows-latest", "ubuntu-latest", "macos-latest" ]

    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup pixi
        uses: prefix-dev/setup-pixi@v0.9.4
        with:
          pixi-version: v0.67.0
          activate-environment: true
          cache: true

      - name: Cache Conan
        uses: actions/cache@v5
        with:
          path: '[".conan/", "build/subprojects/"]'
          key: ${{ runner.os }}-deps-${{ hashFiles('pixi.toml', 'conanfile.py') }}

      - name: Install
        run: pixi run install

      - name: Cache Cmake
        uses: actions/cache@v5
        with:
          path: build/Debug
          key: ${{ runner.os }}-cfg-${{ hashFiles('pixi.toml', 'conanfile.py', '**/CMakeLists.txt') }}

      - name: Configure
        run: pixi run config

      - name: Check
        run: pixi run check

      - name: Build
        run: pixi run build

      - name: Test
        run: pixi run test
